test_that("production configuration and endpoint counts are fixed", {
  config_path <- file.path("..", "..", "config", "era5_mintemp_production.yml")
  skip_if_not(file.exists(config_path), "production config is not included in installed package checks")
  cfg <- read_pipeline_config(config_path)
  expect_identical(unname(cfg$project$profile), "production")
  expect_equal(as.character(cfg$temporal$initial_start_date), "2022-01-01")
  expect_equal(as.character(cfg$temporal$observed_end), "2026-07-26")
  expect_equal(cfg$temporal$source_lag_days, 0)
  expect_equal(cfg$temporal$overlap_days, 0)
  expect_false(isTRUE(cfg$future$daily_enabled))
  dates <- seq(as.Date("2022-01-01"), as.Date("2026-07-26"), by="day")
  expect_length(dates, 1668)
  expect_length(unique(paste(format(dates, "%Y"), format(dates, "%m"))), 55)
  weeks <- assess_iso_week_completeness(dates)
  expect_equal(sum(weeks$complete), 238)
  expect_identical(weeks$week_id[!weeks$complete], "2021-W52")
})

test_that("manifest stage status is canonical and dates are JSON-safe", {
  run_dir <- tempfile("manifest-")
  dir.create(run_dir)
  entry <- update_manifest_stage(list(run_dir=run_dir, completed_stages=character(), pending_stages="x", stage_results=list()), "x", "success", list(status="wrong", dates=as.Date("2022-01-01")))
  expect_identical(names(entry$stage_results$x), c("status", "dates"))
  expect_identical(entry$stage_results$x$status, "success")
  expect_identical(manifest_json_safe(entry$stage_results$x$dates), "2022-01-01")
})
