args <- commandArgs(trailingOnly=TRUE); requested_mode <- if("--mode" %in% args) args[match("--mode",args)+1] else "plan"
pkg <- c(terra="spatial processing", sf="spatial processing", yaml="development", jsonlite="development", digest="development", ISOweek="development", testthat="testing", ncdf4="NetCDF fallback", ecmwfr="CDS download", optparse="CLI")
status <- data.frame(component=names(pkg), purpose=unname(pkg), available=vapply(names(pkg),requireNamespace,logical(1),quietly=TRUE), version=vapply(names(pkg),function(x) if(requireNamespace(x,quietly=TRUE)) as.character(utils::packageVersion(x)) else NA_character_,character(1)),stringsAsFactors=FALSE)
system_info <- data.frame(component=c("R","GDAL","PROJ","GEOS"), purpose="Atlas system library", available=c(TRUE,requireNamespace("terra",quietly=TRUE),requireNamespace("sf",quietly=TRUE),requireNamespace("sf",quietly=TRUE)), version=c(as.character(getRversion()), if(requireNamespace("terra",quietly=TRUE)) terra::gdal() else NA, if(requireNamespace("sf",quietly=TRUE)) as.character(sf::sf_extSoftVersion()["PROJ"]) else NA, if(requireNamespace("sf",quietly=TRUE)) as.character(sf::sf_extSoftVersion()["GEOS"]) else NA),stringsAsFactors=FALSE)
print(rbind(status,system_info)); needed <- c("terra","sf","yaml","jsonlite","digest","ISOweek"); if(requested_mode %in% c("download","stage-requests","retrieve-requests","execute","full")) needed <- c(needed,"ecmwfr"); if(any(!vapply(needed,requireNamespace,logical(1),quietly=TRUE))) quit(status=1)
ncdf4_installed <- requireNamespace("ncdf4",quietly=TRUE)
sample <- Sys.getenv("CDS_DATAGRAB_NETCDF_SAMPLE", "")
terra_netcdf <- if(nzchar(sample) && file.exists(sample) && requireNamespace("terra",quietly=TRUE)) isTRUE(tryCatch({terra::rast(sample); TRUE}, error=function(e) FALSE)) else FALSE
cat("ncdf4 installed: ",ncdf4_installed,"\n",sep=""); cat("ncdf4 NetCDF4/HDF5 read capability: ",ncdf4_installed,"\n",sep=""); cat("terra/GDAL NetCDF read capability: ",terra_netcdf,"\n",sep=""); cat("selected NetCDF reader: ",if(ncdf4_installed) "ncdf4" else if(terra_netcdf) "terra" else "none","\n",sep="")
if(requested_mode %in% c("process","download","full") && !ncdf4_installed && !terra_netcdf) quit(status=1)
