request_definition_hash <- function(dates, cds_area, config, buffer_degrees=NULL, align_to_source_grid=NULL) digest::digest(list(dates=canonical_iso_dates(sort(unique(as.Date(dates)))), dataset=config$cds$dataset_short_name, variable=config$cds$variable, daily_statistic=config$cds$daily_statistic, dataset_version=config$cds$dataset_version %||% NULL, frequency=config$cds$frequency, area=as.numeric(cds_area), source_grid_alignment=isTRUE(align_to_source_grid), buffer_degrees=buffer_degrees), algo="xxhash32")
era5land_request_definition_hash <- function(dates, cds_area, config, variables=.era5land_product_ids()) { digest::digest(list(source_family_id="era5land_daily_mean_utc06",dataset="derived-era5-land-daily-statistics",ordered_variables=vapply(variables,function(id)get_variable_spec(id)$cds_variable,character(1)),year=format(min(as.Date(dates)),"%Y"),month=format(min(as.Date(dates)),"%m"),requested_days=format(sort(unique(as.Date(dates))),"%d"),daily_statistic="daily_mean",frequency="1_hourly",time_zone="utc-06:00",request_area=as.numeric(cds_area),data_format=config$cds$data_format %||% "netcdf",download_format=config$cds$download_format %||% "unarchived"),algo="xxhash32") }
request_adapter_for_spec <- function(spec) if(identical(spec$dataset_adapter,"agera5")) "agera5" else "era5"
request_api_fields <- function(spec) if(identical(spec$source_family_id,"era5land_daily_mean_utc06")) c("product_type","variable","year","month","day","daily_statistic","time_zone","frequency","data_format","download_format","area") else if(identical(request_adapter_for_spec(spec),"agera5")) c("variable","statistic","year","month","day","version","area") else if(identical(spec$id,"era5_lai_low")) c("product_type","variable","year","month","day","time","data_format","download_format","area") else c("product_type","variable","year","month","day","daily_statistic","time_zone","frequency","data_format","download_format","area")
build_variable_requests <- function(planned_dates, cds_area, config, variable_spec=NULL) { spec <- variable_spec %||% get_variable_spec(config$project$dataset_id, config); d <- sort(unique(as.Date(planned_dates))); if(!length(d)) return(list()); if(length(cds_area)!=4 || cds_area[1]<=cds_area[3] || cds_area[2]>=cds_area[4]) stop("CDS area must be north, west, south, east"); g <- split(d, format(d,"%Y-%m")); lapply(g, function(x) { ym <- format(x[1],"%Y-%m"); h <- request_definition_hash(x,cds_area,config,config$spatial$api_bbox_buffer_degrees %||% NULL,config$spatial$align_request_to_source_grid %||% FALSE); transport <- if(identical(request_adapter_for_spec(spec),"agera5")) config$cds$transport_format %||% config$cds$format %||% "netcdf" else config$cds$download_format; container <- config$cds$raw_container_format %||% if(identical(transport,"zip")) "zip" else "netcdf"; target <- sprintf("%s_daily_%s-%s_%s.%s", spec$id, substr(ym,1,4),substr(ym,6,7),substr(h,1,8),container); z <- list(dataset_short_name=spec$dataset_short_name, variable=spec$cds_variable, year=substr(ym,1,4), month=substr(ym,6,7), day=format(x,"%d"), daily_statistic=spec$daily_statistic, area=as.numeric(cds_area), source_grid_alignment=isTRUE(config$spatial$align_request_to_source_grid), source_grid_degrees=spec$source_grid_degrees %||% config$spatial$source_grid_degrees, buffer_degrees=config$spatial$api_bbox_buffer_degrees %||% NULL, request_hash=h, variable_spec_hash=spec$variable_spec_hash, target=target, adapter=request_adapter_for_spec(spec), raw_request_dates=as.character(x), scientific_data_format=config$cds$scientific_data_format %||% "netcdf4", transport_format=transport, raw_container_format=container); if(identical(z$adapter,"agera5")) z$format <- transport else z <- c(z,list(product_type=config$cds$product_type, time=if(identical(spec$id,"era5_lai_low"))"00:00" else NULL, daily_statistic=if(identical(spec$id,"era5_lai_low"))NULL else spec$daily_statistic, time_zone=if(identical(spec$id,"era5_lai_low"))NULL else spec$time_zone, frequency=if(identical(spec$id,"era5_lai_low"))NULL else spec$frequency, data_format=config$cds$data_format, download_format=config$cds$download_format)); z }) }
build_era5_mintemp_requests <- function(planned_dates, cds_area, config) build_variable_requests(planned_dates, cds_area, config, get_variable_spec("era5_mintemp", config))
build_era5land_daily_mean_requests <- function(planned_dates, cds_area, config, variable_ids=.era5land_product_ids()) {
  d <- sort(unique(as.Date(planned_dates))); if (!length(d)) return(list()); if (length(cds_area)!=4 || cds_area[1]<=cds_area[3] || cds_area[2]>=cds_area[4]) stop("CDS area must be north, west, south, east",call.=FALSE)
  if (!identical(variable_ids, .era5land_product_ids())) variable_ids <- as.character(variable_ids)
  unknown <- setdiff(variable_ids,.era5land_product_ids())
  if (length(unknown)) stop("Unknown ERA5-Land product identifier: ",paste(unknown,collapse=", "),call.=FALSE)
  if (!setequal(variable_ids,.era5land_product_ids())) stop("ERA5-Land family requests must contain all eight registered products",call.=FALSE)
  variable_ids <- .era5land_product_ids()
  g <- split(d,format(d,"%Y-%m")); lapply(g,function(x) { ym <- format(x[1],"%Y-%m"); h <- era5land_request_definition_hash(x,cds_area,config,variable_ids); vars <- vapply(variable_ids,function(id)get_variable_spec(id)$cds_variable,character(1)); target <- sprintf("era5land_daily_mean_utc06_%s-%s_%s.nc",substr(ym,1,4),substr(ym,6,7),h); list(source_family_id="era5land_daily_mean_utc06",dataset_short_name="derived-era5-land-daily-statistics",product_type=unname(config$cds$product_type %||% "reanalysis"),variable=vars,requested_variables=vars,product_ids=variable_ids,year=substr(ym,1,4),month=substr(ym,6,7),day=format(x,"%d"),request_start=as.character(min(x)),request_end=as.character(max(x)),daily_statistic="daily_mean",time_zone="utc-06:00",frequency="1_hourly",data_format=unname(config$cds$data_format %||% "netcdf"),download_format=unname(config$cds$download_format %||% "unarchived"),area=as.numeric(cds_area),source_grid_alignment=isTRUE(config$spatial$align_request_to_source_grid),source_grid_degrees=config$spatial$source_grid_degrees %||% 0.1,buffer_degrees=config$spatial$api_bbox_buffer_degrees %||% NULL,request_hash=h,raw_target=target,target=target,raw_request_dates=as.character(x),adapter="era5land",variable_spec_hash=digest::digest(vapply(variable_ids,function(id)get_variable_spec(id)$variable_spec_hash,character(1)),algo="xxhash32")) })
}
validate_cds_request_structure <- function(request) { stopifnot(is.list(request)); required <- c("dataset_short_name","variable","year","month","day","daily_statistic","area","target"); if(!all(required %in% names(request))) stop("Missing CDS request fields"); if(identical(request$source_family_id,"era5land_daily_mean_utc06")){if(request$dataset_short_name!="derived-era5-land-daily-statistics"||!is.character(request$variable)||length(request$variable)!=8L||request$daily_statistic!="daily_mean"||request$time_zone!="utc-06:00"||request$frequency!="1_hourly"||request$data_format!="netcdf"||request$download_format!="unarchived")stop("Invalid ERA5-Land source-family request");if(!identical(as.character(request$requested_variables),as.character(request$variable)))stop("requested_variables must match variable order");return(TRUE)}; spec <- get_variable_spec(request$variable); if(request$dataset_short_name!=spec$dataset_short_name||request$variable!=spec$cds_variable||request$daily_statistic!=spec$daily_statistic) stop("Invalid request specification"); if(!grepl("^\\d{4}$",request$year)||!grepl("^\\d{2}$",request$month)||any(!grepl("^\\d{2}$",request$day))||any(as.integer(request$day)<1|as.integer(request$day)>31)||any(is.na(as.Date(paste(request$year,request$month,request$day,sep="-"),format="%Y-%m-%d")))) stop("Invalid request date fields"); if(length(request$area)!=4||request$area[1]<=request$area[3]||request$area[2]>=request$area[4]) stop("Invalid area"); if(identical(request_adapter_for_spec(spec),"agera5")){if(!is.list(request$statistic)||!identical(request$statistic,list(spec$daily_statistic))||!identical(as.character(request$version),"2_0"))stop("Invalid AgERA5 request schema")}else if(is.null(request$product_type)||request$data_format!="netcdf"||request$download_format!="unarchived") stop("Invalid ERA5 request fields"); TRUE }
cds_api_fields <- c("product_type","variable","year","month","day","daily_statistic","time_zone","frequency","data_format","download_format","area")
cds_internal_fields <- c("source_grid_alignment","buffer_degrees","source_grid_degrees","request_extent_source","request_hash","target","target_filename","resolved_target_path","planned_dates","adapter","variable_spec_hash","raw_request_dates")
validate_cds_api_payload <- function(payload) {
  if(!is.list(payload)) stop("CDS API payload must be a list",call.=FALSE); fields <- if("statistic" %in% names(payload)) request_api_fields(get_variable_spec("agera5_relhum_min")) else if("time" %in% names(payload)) request_api_fields(get_variable_spec("era5_lai_low")) else cds_api_fields; unexpected <- setdiff(names(payload),fields); if(length(unexpected)) stop("Unexpected fields in CDS API payload: ",paste(unexpected,collapse=", "),call.=FALSE); missing <- setdiff(fields,names(payload)); if(length(missing)) stop("CDS API payload is missing required fields: ",paste(missing,collapse=", "),call.=FALSE)
  if ("statistic" %in% names(payload)) { if (!is.character(payload$variable) || !is.list(payload$statistic) || !is.character(payload$statistic[[1]]) || !is.character(payload$version) || !is.character(payload$year) || !is.character(payload$month)) stop("AgERA5 API fields have invalid types", call.=FALSE) } else { char_fields <- setdiff(fields,c("day","area")); if(any(!vapply(payload[char_fields],function(x)is.character(x)&&length(x)>=1L,logical(1)))) stop("CDS API character fields must be character values",call.=FALSE) }; if(!is.character(payload$day)||!length(payload$day)) stop("CDS API day must be a character vector",call.=FALSE); if(!is.numeric(payload$area)||length(payload$area)!=4L||payload$area[1]<=payload$area[3]||payload$area[4]<=payload$area[2]) stop("CDS API area must be north, west, south, east",call.=FALSE); if(any(cds_internal_fields %in% names(payload))) stop("Internal pipeline metadata must not be sent to CDS",call.=FALSE); TRUE
}
build_cds_api_payload <- function(request_record) { spec <- if(identical(request_record$source_family_id,"era5land_daily_mean_utc06")) get_variable_spec("era5land_tmean") else get_variable_spec(request_record$variable); fields <- request_api_fields(spec); missing <- setdiff(fields,names(request_record)); if(length(missing)) stop("Request record is missing required CDS fields: ",paste(missing,collapse=", "),call.=FALSE); payload <- request_record[fields]; if(identical(request_adapter_for_spec(spec),"agera5")) names(payload)[names(payload)=="format"] <- "format"; validate_cds_api_payload(payload); payload }
write_cds_request_manifests <- function(requests, run_dir) { fs::dir_create(run_dir,recurse=TRUE); rows <- if(length(requests)) do.call(rbind,lapply(requests,function(x) data.frame(source_family_id=x$source_family_id %||% NA_character_,request_hash=x$request_hash,request_start=x$request_start %||% min(x$raw_request_dates),request_end=x$request_end %||% max(x$raw_request_dates),requested_variables=paste(x$requested_variables %||% x$variable,collapse=";"),daily_statistic=x$daily_statistic,frequency=x$frequency %||% NA_character_,time_zone=x$time_zone %||% NA_character_,request_area=paste(x$area,collapse=","),raw_target=x$raw_target %||% x$target,year=x$year,month=x$month,days=paste(x$day,collapse=","),area=paste(x$area,collapse=","),target=x$target,stringsAsFactors=FALSE))) else data.frame(); utils::write.csv(rows,file.path(run_dir,"request_manifest.csv"),row.names=FALSE); jsonlite::write_json(requests,file.path(run_dir,"request_manifest.json"),pretty=TRUE,auto_unbox=TRUE); invisible(rows) }
