inventory_grid_directory <- function(directory, prefix, timestep=c("daily","weekly"), include_estimated=TRUE) {
  timestep <- match.arg(timestep); fs <- if (dir.exists(directory)) list.files(directory, full.names=TRUE, ignore.case=TRUE) else character(); x <- if(length(fs)) do.call(rbind, lapply(fs, parse_grid_filename, expected_prefix=prefix)) else parse_grid_filename(file.path(directory, "__empty__"), prefix); x <- x[x$timestep == timestep | is.na(x$timestep), , drop=FALSE]; if(!include_estimated) x <- x[!x$estimated, , drop=FALSE]; x
}
inventory_daily_products <- function(daily_dir, prefix, template_path, validate_rasters=TRUE, config=NULL) {
  files <- if(dir.exists(daily_dir)) list.files(daily_dir, pattern="\\.(tif|tiff)$", full.names=TRUE, ignore.case=TRUE) else character()
  template <- terra::rast(template_path)
  support_info <- if (!is.null(config) && exists("era5land_support_mask_info", mode = "function")) era5land_support_mask_info(config, template, required = FALSE) else NULL
  support_mask <- if (is.null(support_info)) NULL else support_info$mask
  if(!length(files)) return(data.frame(path=character(),filename=character(),date=as.Date(character()),estimated=logical(),filename_valid=logical(),raster_readable=logical(),geometry_valid=logical(),crs_valid=logical(),value_range_valid=logical(),template_coverage_complete=logical(),observed_valid=logical(),validation_message=character(),valid=logical(),stringsAsFactors=FALSE))
  rows <- lapply(files, function(path) {
    p <- parse_grid_filename(path,prefix); filename_valid <- isTRUE(p$valid[1]) && identical(p$timestep[1],"daily"); readable <- geometry <- crs <- range_ok <- complete <- FALSE; msg <- if(!filename_valid) p$parse_message[1] else ""
    if(filename_valid && validate_rasters) { r <- tryCatch(terra::rast(path),error=function(e)e); if(inherits(r,"error")) msg <- conditionMessage(r) else { readable <- TRUE; geometry <- terra::nlyr(r)==1 && terra::nrow(r)==terra::nrow(template) && terra::ncol(r)==terra::ncol(template) && all(abs(as.vector(terra::ext(r))-as.vector(terra::ext(template)))<1e-8); crs <- identical(terra::crs(r),terra::crs(template)); range_result <- validate_variable_value_range(r, get_variable_spec((config$project$dataset_id %||% prefix),config)); range_ok <- isTRUE(range_result$valid); if(!range_ok) msg <- range_result$message; g <- tryCatch(validate_template_coverage(r,template,FALSE,support_mask=support_mask),error=function(e)e); complete <- !inherits(g,"error") && isTRUE(g$complete); if(!complete) msg <- paste0("incomplete_template_coverage_missing_",if(inherits(g,"error")) NA else g$missing_supported_count) } } else if(filename_valid) { readable <- geometry <- crs <- range_ok <- complete <- NA }
    observed <- !isTRUE(p$estimated[1]) && filename_valid && readable && geometry && crs && range_ok && complete
    data.frame(path=path,filename=basename(path),date=p$date[1],estimated=p$estimated[1],filename_valid=filename_valid,raster_readable=readable,geometry_valid=geometry,crs_valid=crs,value_range_valid=range_ok,template_coverage_complete=complete,observed_valid=observed,validation_message=if(nzchar(msg)) msg else if(observed) "ok" else "invalid",valid=observed,stringsAsFactors=FALSE)
  })
  do.call(rbind,rows)
}

quarantine_invalid_daily_outputs <- function(inventory, paths, run_id, dry_run=FALSE) {
  invalid <- inventory[!inventory$observed_valid & inventory$filename_valid & !inventory$estimated, , drop=FALSE]; if(!nrow(invalid)) return(data.frame())
  if(!file.exists(paths$root_marker)) stop("Storage root marker is missing",call.=FALSE); marker <- jsonlite::read_json(paths$root_marker,simplifyVector=TRUE); if(is.null(marker$application)||marker$application!="cds-datagrab") stop("Invalid storage root marker",call.=FALSE)
  qdir <- file.path(paths$dataset_root,"quarantine","daily",run_id); if(!dry_run) fs::dir_create(qdir,recurse=TRUE)
  rows <- lapply(seq_len(nrow(invalid)), function(i) { orig <- normalizePath(invalid$path[i],winslash="/",mustWork=TRUE); if(!.descendant(orig,paths$dataset_root) || !.descendant(orig,paths$daily_dir)) stop("Refusing to quarantine file outside active daily directory",call.=FALSE); dest <- file.path(qdir,basename(orig)); if(!dry_run) fs::file_move(orig,dest); data.frame(original_path=orig,quarantine_path=dest,date=invalid$date[i],validation_failure=invalid$validation_message[i],checksum=unname(tools::md5sum(if(dry_run) orig else dest)),move_time=as.character(Sys.time()),planned=dry_run,stringsAsFactors=FALSE) })
  out <- do.call(rbind,rows); if(!dry_run) utils::write.csv(out,file.path(qdir,"quarantine_manifest.csv"),row.names=FALSE); out
}
summarize_grid_inventory <- function(inventory) { ok <- inventory$valid; obs <- inventory[ok & !inventory$estimated,]; est <- inventory[ok & inventory$estimated,]; ds <- sort(unique(obs$date)); list(n_files=nrow(inventory), observed_files=nrow(obs), estimated_files=nrow(est), nonconforming=inventory[!ok,], duplicate_observed=ds[duplicated(ds)], duplicate_estimated=est$date[duplicated(est$date)], conflicts=intersect(obs$date, est$date), earliest_observed=if(length(ds)) min(ds) else as.Date(NA), latest_observed=if(length(ds)) max(ds) else as.Date(NA), earliest_estimated=if(nrow(est)) min(est$date) else as.Date(NA), latest_estimated=if(nrow(est)) max(est$date) else as.Date(NA), internal_gaps=if(length(ds)>1) setdiff(seq(min(ds), max(ds), by="day"), ds) else as.Date(character())) }
find_inventory_conflicts <- function(inventory) { s <- summarize_grid_inventory(inventory); list(duplicate_observed=s$duplicate_observed, duplicate_estimated=s$duplicate_estimated, observed_estimated=s$conflicts, nonconforming=s$nonconforming) }
