is_netcdf_path <- function(path) grepl("\\.(nc|netcdf)$", basename(path), ignore.case=TRUE)
is_supported_raw_path <- function(path) is_netcdf_path(path) | grepl("\\.(zip|grib)$", basename(path), ignore.case=TRUE)

select_active_raw_inputs <- function(request_records, download_results=NULL, raw_inventory=NULL) {
  if(!length(request_records)) return(list(active=character(),reused_matching=character(),unmatched=raw_inventory %||% character(),superseded=raw_inventory %||% character(),invalid=character()))
  targets <- vapply(request_records,function(x)x$target,character(1)); raw_paths <- if(is.null(raw_inventory)) character() else if(is.data.frame(raw_inventory)) raw_inventory$path else raw_inventory; raw_names <- basename(raw_paths); matching <- character(); active <- character(); reused <- character(); invalid <- character()
  raw_paths <- raw_paths[is_supported_raw_path(raw_paths)]
  raw_names <- basename(raw_paths)
  for(req in request_records) { stem <- tools::file_path_sans_ext(basename(req$target)); candidates <- raw_paths[tools::file_path_sans_ext(raw_names)==stem | raw_names==basename(req$target)]; matching <- c(matching,candidates); if(length(candidates)>1L) { checks <- vapply(candidates,function(p)digest::digest(file=p,algo="sha256"),character(1)); candidates <- candidates[checks==checks[[1]]] }; if(length(candidates)!=1L) next; p <- candidates[[1]]; vr <- validate_downloaded_target(p,req); content_valid <- !identical(req$adapter %||% "", "agera5") || !identical(vr$format, "zip") || agera5_archive_matches_request(p,req); if(vr$valid && content_valid) { active <- c(active,p); if(!is.null(download_results) && any(download_results$target_filename==req$target & download_results$status=="reused_existing",na.rm=TRUE)) reused <- c(reused,p) } else invalid <- c(invalid,p) }
  unmatched <- setdiff(raw_paths,unique(matching)); superseded <- unmatched[grepl("_[0-9a-fA-F]{8}\\.(nc|netcdf|zip)$",basename(unmatched),ignore.case=TRUE)]; list(active=unique(active),reused_matching=unique(reused),unmatched=unmatched,superseded=superseded,invalid=unique(invalid))
}

map_dates_to_active_raw_sources <- function(raw_inputs, request_records) {
  rows <- list(); for(req in request_records) { stem <- tools::file_path_sans_ext(basename(req$target)); candidates <- raw_inputs[tools::file_path_sans_ext(basename(raw_inputs))==stem]; if(!length(candidates)) next; p <- candidates[[1]]; ds <- canonical_iso_dates(sprintf("%s-%s-%s",req$year,req$month,req$day), "raw_request_dates"); for(d in ds) rows[[length(rows)+1L]] <- data.frame(date=d,selected_raw_source=p,source_path=p,request_hash=req$request_hash %||% NA_character_,raw_request_start=min(ds),raw_request_end=max(ds),decoded_source_start=NA_character_,decoded_source_end=NA_character_,mapping_reason="exact_active_request_hash",stringsAsFactors=FALSE) }
  if(!length(rows)) return(data.frame(date=character(),selected_raw_source=character(),source_path=character(),request_hash=character(),raw_request_start=character(),raw_request_end=character(),decoded_source_start=character(),decoded_source_end=character(),mapping_reason=character(),stringsAsFactors=FALSE)); out <- do.call(rbind,rows); out$date <- canonical_iso_dates(out$date,"date_source_map$date"); if(anyDuplicated(out$date)) stop("Multiple active raw sources provide the same date",call.=FALSE); out
}

normalize_path_key <- function(path) tolower(gsub("\\\\", "/", normalizePath(path, winslash="/", mustWork=FALSE)))
build_request_dates <- function(request_entry) { if(is.null(request_entry)||!all(c("year","month","day")%in%names(request_entry)))stop("Request entry is missing year, month, or day",call.=FALSE);d<-normalize_date_vector(sprintf("%s-%s-%s",request_entry$year,request_entry$month,request_entry$day),"raw_request_dates");keys<-format(d,"%Y-%m-%d");if(!identical(keys,sort(unique(keys)))||anyDuplicated(keys))stop("Request dates must be canonical, ordered, and unique",call.=FALSE);d }
request_entry_for_raw <- function(raw_path, request_manifest) { if(!length(request_manifest))stop("No request-manifest entries are available for raw path: ",raw_path,call.=FALSE);target<-tools::file_path_sans_ext(basename(raw_path));hits<-Filter(function(x)tools::file_path_sans_ext(as.character(x$target))==target,request_manifest);if(length(hits)!=1L)stop("Expected exactly one request-manifest entry for raw path: ",raw_path,call.=FALSE);hits[[1]] }
selected_dates_for_raw <- function(raw_path, date_source_map) { if(is.null(date_source_map)||!nrow(date_source_map))return(as.Date(character()));key<-normalize_path_key(raw_path);z<-date_source_map[normalize_path_key(date_source_map$selected_raw_source)==key,,drop=FALSE];if(!nrow(z))return(as.Date(character()));d<-normalize_date_vector(z$date,"dates_to_process");keys<-format(d,"%Y-%m-%d");if(anyDuplicated(keys))stop("Duplicate selected dates for raw path: ",raw_path,call.=FALSE);if(!identical(keys,sort(keys)))stop("Selected dates are not chronological for raw path: ",raw_path,call.=FALSE);d }
validate_date_source_map <- function(date_source_map, active_raw_inputs, request_records) { if(is.null(date_source_map)||!nrow(date_source_map))return(TRUE);d<-canonical_iso_dates(date_source_map$date,"date_source_map$date");if(anyDuplicated(d))stop("Each selected date must map to exactly one active raw file",call.=FALSE);source_col<-if("selected_raw_source"%in%names(date_source_map))"selected_raw_source"else"source_path";if(any(!normalize_path_key(date_source_map[[source_col]])%in%normalize_path_key(active_raw_inputs)))stop("date_source_map contains a raw path that is not active",call.=FALSE);for(p in unique(date_source_map[[source_col]])){req<-request_entry_for_raw(p,request_records);rd<-build_request_dates(req);sd<-selected_dates_for_raw(p,date_source_map);if(!all(canonical_iso_dates(sd)%in%canonical_iso_dates(rd)))stop("Selected dates are absent from raw request dates for: ",p,call.=FALSE);if(!is.null(date_source_map$request_hash)&&any(date_source_map[[source_col]]==p&date_source_map$request_hash!=req$request_hash))stop("Request hash and request-manifest entry disagree for: ",p,call.=FALSE)};TRUE }
