variable_spec_hash <- function(spec) { x <- spec[c("id","short_name","source_family_id","dataset_short_name","cds_variable","netcdf_variable_names","source_units","output_units","daily_statistic","time_zone","frequency","unit_conversion","spatial_interpolation","weekly_statistic","hard_valid_range","soft_warning_range","soil_layer","metadata_notes")]; digest::digest(x, algo="xxhash32") }
.variable_spec_mintemp <- function() { x <- list(id="era5_mintemp", short_name="mintemp", long_name="2 metre temperature", dataset_short_name="derived-era5-single-levels-daily-statistics", cds_variable="2m_temperature", netcdf_variable_names=c("t2m","2m_temperature"), source_units="K", output_units="degrees C", soil_layer=NULL, daily_statistic="daily_minimum", time_zone="utc+00:00", frequency="6_hourly", unit_conversion="kelvin_to_celsius", spatial_interpolation="bilinear", weekly_statistic="minimum", hard_valid_range=c(-100,70), soft_warning_range=NULL, daily_filename_prefix="mintemp", weekly_filename_prefix="mintemp"); x$variable_spec_hash <- variable_spec_hash(x); x }
.variable_spec_soilmoist <- function() { x <- list(id="era5_soilmoist", short_name="soilmoist", long_name="Volumetric soil water layer 1", dataset_short_name="derived-era5-single-levels-daily-statistics", cds_variable="volumetric_soil_water_layer_1", netcdf_variable_names=c("swvl1","volumetric_soil_water_layer_1"), source_units="m3 m-3", output_units="m3 m-3", soil_layer=list(top_cm=0,bottom_cm=7), daily_statistic="daily_mean", time_zone="utc+00:00", frequency="6_hourly", unit_conversion="identity", spatial_interpolation="bilinear", weekly_statistic="mean", hard_valid_range=c(0,1), soft_warning_range=c(0.01,0.80), daily_filename_prefix="soilmoist", weekly_filename_prefix="soilmoist"); x$variable_spec_hash <- variable_spec_hash(x); x }
.variable_spec_lai_low <- function() { x <- list(id="era5_lai_low", short_name="lai_low", long_name="Leaf area index, low vegetation", dataset_short_name="reanalysis-era5-single-levels", cds_variable="leaf_area_index_low_vegetation", netcdf_variable_names=c("lai_lv","leaf_area_index_low_vegetation"), source_units="m2 m-2", output_units="m2 m-2", soil_layer=NULL, daily_statistic="instantaneous_00_utc", time_zone="utc+00:00", frequency="monthly", unit_conversion="identity", spatial_interpolation="bilinear", weekly_statistic="mean", hard_valid_range=c(0,20), source_hard_valid_range=c(-0.01,20), soft_warning_range=NULL, daily_filename_prefix="lai_low", weekly_filename_prefix="lai_low", dataset_adapter="era5", product_type="direct", temporal_character="monthly_climatology", interannual_variability="absent", source_grid_degrees=0.25); x$variable_spec_hash <- variable_spec_hash(x); x }
.variable_spec_relhum_min <- function() { x <- list(id="agera5_relhum_min", short_name="relhum_min", long_name="2 m relative humidity derived, 24-hour minimum", dataset_short_name="sis-agrometeorological-indicators", cds_variable="2m_relative_humidity_derived", netcdf_variable_names=c("relhum_min","relative_humidity_2m_min","2m_relative_humidity_derived","RHmin"), source_units="percent", output_units="percent", soil_layer=NULL, daily_statistic="24_hour_minimum", time_zone="local_time", frequency="daily", unit_conversion="identity", spatial_interpolation="bilinear", weekly_statistic="mean", hard_valid_range=c(0,100), source_hard_valid_range=c(-1,101), soft_warning_range=NULL, daily_filename_prefix="relhum_min", weekly_filename_prefix="relhum_min", dataset_adapter="agera5", product_type="direct_precomputed_derived_indicator", source_family="AgERA5", source_grid_degrees=0.1, daily_time_basis="local_time", spatial_processing="AgERA5_downscaled_bias_adjusted", model_alias="relhum"); x$variable_spec_hash <- variable_spec_hash(x); x }
.era5land_product_ids <- function() c("era5land_tmean","era5land_soiltemp_l1_mean","era5land_soiltemp_l2_mean","era5land_soilwater_l1_mean","era5land_soilwater_l2_mean","era5land_surface_pressure_mean","era5land_lai_high_mean","era5land_lai_low_mean")
.era5land_spec <- function(id) {
  family <- "era5land_daily_mean_utc06"; common <- list(source_family_id=family,dataset_short_name="derived-era5-land-daily-statistics",daily_statistic="daily_mean",time_zone="utc-06:00",frequency="1_hourly",spatial_interpolation="bilinear",weekly_statistic="mean",dataset_adapter="era5land",product_type="daily_mean",source_grid_degrees=0.1)
  rows <- list(
    era5land_tmean=list(short_name="tmean",long_name="ERA5-Land mean 2 metre temperature",cds_variable="2m_temperature",netcdf_variable_names=c("t2m","2t","2m_temperature"),source_units="K",output_units="degrees C",unit_conversion="kelvin_to_celsius",soil_layer=NULL,hard_valid_range=c(-100,70),source_hard_valid_range=c(150,380),daily_meaning="Arithmetic mean of hourly ERA5-Land values over the UTC-06 calendar day",filename_prefix="era5land_tmean"),
    era5land_soiltemp_l1_mean=list(short_name="soiltemp_l1_mean",long_name="ERA5-Land soil temperature level 1 daily mean",cds_variable="soil_temperature_level_1",netcdf_variable_names=c("stl1","soil_temperature_level_1"),source_units="K",output_units="degrees C",unit_conversion="kelvin_to_celsius",soil_layer=list(top_cm=0,bottom_cm=7),hard_valid_range=c(-100,80),source_hard_valid_range=c(150,380),filename_prefix="era5land_soiltemp_l1_mean"),
    era5land_soiltemp_l2_mean=list(short_name="soiltemp_l2_mean",long_name="ERA5-Land soil temperature level 2 daily mean",cds_variable="soil_temperature_level_2",netcdf_variable_names=c("stl2","soil_temperature_level_2"),source_units="K",output_units="degrees C",unit_conversion="kelvin_to_celsius",soil_layer=list(top_cm=7,bottom_cm=28),hard_valid_range=c(-100,80),source_hard_valid_range=c(150,380),filename_prefix="era5land_soiltemp_l2_mean"),
    era5land_soilwater_l1_mean=list(short_name="soilwater_l1_mean",long_name="ERA5-Land volumetric soil water layer 1 daily mean",cds_variable="volumetric_soil_water_layer_1",netcdf_variable_names=c("swvl1","volumetric_soil_water_layer_1"),source_units="m3 m-3",output_units="m3 m-3",unit_conversion="identity",soil_layer=list(top_cm=0,bottom_cm=7),hard_valid_range=c(0,1),source_hard_valid_range=c(0,1),filename_prefix="era5land_soilwater_l1_mean"),
    era5land_soilwater_l2_mean=list(short_name="soilwater_l2_mean",long_name="ERA5-Land volumetric soil water layer 2 daily mean",cds_variable="volumetric_soil_water_layer_2",netcdf_variable_names=c("swvl2","volumetric_soil_water_layer_2"),source_units="m3 m-3",output_units="m3 m-3",unit_conversion="identity",soil_layer=list(top_cm=7,bottom_cm=28),hard_valid_range=c(0,1),source_hard_valid_range=c(0,1),filename_prefix="era5land_soilwater_l2_mean"),
    era5land_surface_pressure_mean=list(short_name="surface_pressure_mean",long_name="ERA5-Land surface pressure daily mean",cds_variable="surface_pressure",netcdf_variable_names=c("sp","surface_pressure"),source_units="Pa",output_units="kPa",unit_conversion="pascal_to_kilopascal",soil_layer=NULL,hard_valid_range=c(20,115),source_hard_valid_range=c(20000,115000),filename_prefix="era5land_surface_pressure_mean"),
    era5land_lai_high_mean=list(short_name="lai_high_mean",long_name="ERA5-Land high-vegetation leaf area index daily mean",cds_variable="leaf_area_index_high_vegetation",netcdf_variable_names=c("lai_hv","leaf_area_index_high_vegetation"),source_units="m2 m-2",output_units="m2 m-2",unit_conversion="identity",soil_layer=NULL,hard_valid_range=c(0,20),source_hard_valid_range=c(0,20),filename_prefix="era5land_lai_high_mean",metadata_notes="Monthly climatology: monthly variability is represented, but interannual variability is absent; identical consecutive daily layers are permitted."),
    era5land_lai_low_mean=list(short_name="lai_low_mean",long_name="ERA5-Land low-vegetation leaf area index daily mean",cds_variable="leaf_area_index_low_vegetation",netcdf_variable_names=c("lai_lv","leaf_area_index_low_vegetation"),source_units="m2 m-2",output_units="m2 m-2",unit_conversion="identity",soil_layer=NULL,hard_valid_range=c(0,20),source_hard_valid_range=c(0,20),filename_prefix="era5land_lai_low_mean",metadata_notes="Monthly climatology: monthly variability is represented, but interannual variability is absent; identical consecutive daily layers are permitted.")
  )
  z <- c(common, rows[[id]]); z$id <- id; z$weekly_filename_prefix <- z$filename_prefix; z$daily_filename_prefix <- z$filename_prefix; z$soft_warning_range <- NULL; z$daily_time_zone <- z$time_zone; z$daily_sampling_frequency <- z$frequency; z$variable_spec_hash <- variable_spec_hash(z); z
}
get_variable_spec <- function(variable_id, config=NULL) { id <- as.character(variable_id %||% if(!is.null(config)) config$project$dataset_id else ""); if(id %in% .era5land_product_ids()) return(.era5land_spec(id)); if(id %in% c("era5_mintemp","mintemp","2m_temperature","t2m")) return(.variable_spec_mintemp()); if(id %in% c("era5_soilmoist","soilmoist","volumetric_soil_water_layer_1")) return(.variable_spec_soilmoist()); if(id %in% c("era5_lai_low","lai_low","leaf_area_index_low_vegetation","lai_lv")) return(.variable_spec_lai_low()); if(id %in% c("agera5_relhum_min","relhum_min","relhum","2m_relative_humidity_derived")) return(.variable_spec_relhum_min()); stop("Unknown variable_id: ", id, call.=FALSE) }
resolve_netcdf_variable <- function(nc_metadata, variable_spec) { candidates <- intersect(variable_spec$netcdf_variable_names, names(nc_metadata$variables)); if(!length(candidates)) stop("No NetCDF variable matched aliases: ", paste(variable_spec$netcdf_variable_names, collapse=", "), call.=FALSE); if(length(candidates)>1L) { a <- lapply(candidates, function(n) nc_metadata$variables[[n]]$data_signature %||% nc_metadata$variables[[n]]$dimensions); if(!identical(a[[1]],a[[2]])) stop("NetCDF variable aliases are ambiguous and refer to different data",call.=FALSE) }; candidates[[1]] }
normalize_source_units <- function(units) { if(length(units)!=1L||is.na(units)||!nzchar(trimws(units))) return(NA_character_); x<-trimws(as.character(units)); x<-chartr("\u2070\u00b9\u00b2\u00b3\u2074\u2075\u2076\u2077\u2078\u2079\u207b","0123456789-",x); x<-gsub("[\u00d7\u00b7\u22c5]"," ",x); x<-gsub("[[:space:]]+"," ",x); x<-gsub("\\s*[/]\\s*","/",x); x<-gsub("\\s*[\\^]\\s*","^",x); x<-gsub("\\*\\*","^",x); x<-tolower(trimws(x)); if(x%in%c("1","1/1","dimensionless"))return("m3 m-3"); if(x%in%c("m2/m2","m^2/m^2","m2 m-2","m^2 m^-2","m^2 m-2"))return("m2 m-2"); if(x%in%c("%","percent","percentage"))return("percent"); if(x%in%c("m3/m3","m^3/m^3","m3 m-3","m^3 m^-3","m^3 m-3","m3 m^ -3"))return("m3 m-3"); if(x%in%c("k","kelvin"))return("K"); if(x%in%c("pa","pascal","pascals"))return("Pa"); if(x%in%c("kpa","kilopascal","kilopascals"))return("kPa"); x }
convert_source_units <- function(x, variable_spec, source_units=NULL) { expected <- normalize_source_units(variable_spec$source_units); actual <- normalize_source_units(source_units); lai_dimensionless <- variable_spec$id=="era5_lai_low" && tolower(trimws(as.character(source_units%||%"")))%in%c("1","dimensionless"); if(!is.null(source_units)&&!identical(actual,expected)&&!lai_dimensionless)stop("Unsupported source units: ",source_units,call.=FALSE); if(variable_spec$unit_conversion=="kelvin_to_celsius")return(x-273.15); if(variable_spec$unit_conversion=="pascal_to_kilopascal")return(x/1000); if(variable_spec$unit_conversion=="identity")return(x); stop("Unsupported unit conversion: ",variable_spec$unit_conversion,call.=FALSE) }
.source_validation_tolerance <- 1e-10 # Absolute source-unit tolerance for floating-point artifacts at finite hard bounds.
validate_source_values <- function(x, variable_spec, source_hard_min=variable_spec$source_hard_valid_range[1] %||% -Inf, source_hard_max=variable_spec$source_hard_valid_range[2] %||% Inf, tolerance=.source_validation_tolerance) {
  if (length(source_hard_min) != 1L || length(source_hard_max) != 1L || anyNA(c(source_hard_min, source_hard_max)) || source_hard_min > source_hard_max) stop("Source hard bounds must be ordered non-missing scalars", call.=FALSE)
  if (length(tolerance) != 1L || !is.finite(tolerance) || tolerance < 0) stop("Source validation tolerance must be one finite non-negative value", call.=FALSE)
  raw <- as.numeric(x); finite <- is.finite(raw); raw_finite <- raw[finite]
  if(!length(raw_finite)) stop("Source variable has no finite values",call.=FALSE)
  materially_low <- if (is.finite(source_hard_min)) finite & raw < source_hard_min - tolerance else rep(FALSE, length(raw))
  materially_high <- if (is.finite(source_hard_max)) finite & raw > source_hard_max + tolerance else rep(FALSE, length(raw))
  if(any(materially_low | materially_high)) stop("Source values outside sanity range [",source_hard_min,", ",source_hard_max,"]",call.=FALSE)
  normalized <- raw
  clamp_low <- if (is.finite(source_hard_min)) finite & normalized < source_hard_min else rep(FALSE, length(normalized))
  clamp_high <- if (is.finite(source_hard_max)) finite & normalized > source_hard_max else rep(FALSE, length(normalized))
  normalized[clamp_low] <- source_hard_min; normalized[clamp_high] <- source_hard_max
  if (!is.null(dim(x))) { dim(normalized) <- dim(x); dimnames(normalized) <- dimnames(x) } else names(normalized) <- names(x)
  normalized_finite <- as.numeric(normalized)[finite]
  list(values=normalized,source_raw_minimum=min(raw_finite),source_raw_maximum=max(raw_finite),source_minimum=min(normalized_finite),source_maximum=max(normalized_finite),source_non_na_count=length(normalized_finite),source_lower_clamped_count=sum(clamp_low),source_upper_clamped_count=sum(clamp_high),source_validation_tolerance=tolerance,source_hard_range_valid=TRUE)
}
validate_variable_value_range <- function(x, variable_spec) { if(is.character(x)&&length(x)==1L&&file.exists(x))x<-terra::rast(x); z<-if(inherits(x,"SpatRaster"))as.numeric(terra::values(x,mat=FALSE))else as.numeric(x); finite<-is.finite(z); hard<-as.numeric(variable_spec$hard_valid_range); valid_values<-z[finite]; below<-sum(valid_values<hard[1]); above<-sum(valid_values>hard[2]); nonfinite_non_na<-sum(!finite & !is.na(z)); valid<-length(valid_values)>0L&&!below&&!above&&!nonfinite_non_na; list(valid=valid,expected_minimum=hard[1],expected_maximum=hard[2],observed_minimum=if(length(valid_values))min(valid_values)else NA_real_,observed_maximum=if(length(valid_values))max(valid_values)else NA_real_,below_count=below,above_count=above,total_cells=length(z),finite_non_nodata_cells=length(valid_values),na_nodata_cells=sum(is.na(z)),nonfinite_non_na_cells=nonfinite_non_na,message=if(valid)"ok"else sprintf("value range invalid: observed_min=%s observed_max=%s expected_min=%s expected_max=%s below_count=%d above_count=%d",format(if(length(valid_values))min(valid_values)else NA_real_,trim=TRUE),format(if(length(valid_values))max(valid_values)else NA_real_,trim=TRUE),hard[1],hard[2],below,above)) }
validate_variable_values <- function(x, variable_spec, tolerance=1e-6) { z<-as.numeric(x);finite<-is.finite(z);hard<-variable_spec$hard_valid_range;if(variable_spec$id=="era5_soilmoist"){z[finite&z<hard[1]&z>=hard[1]-tolerance]<-hard[1];z[finite&z>hard[2]&z<=hard[2]+tolerance]<-hard[2]};range_check<-validate_variable_value_range(z,variable_spec);hard_valid<-range_check$valid;warning_range<-variable_spec$soft_warning_range;soft_warning<-!is.null(warning_range)&&any(finite&(z<warning_range[1]|z>warning_range[2]));if(!hard_valid)stop("Values outside hard valid range [",hard[1],", ",hard[2],"]",call.=FALSE);qs<-if(any(finite))stats::quantile(z[finite],probs=c(0,.25,.5,.75,1),names=FALSE,na.rm=TRUE)else rep(NA_real_,5);list(values=z,minimum=if(any(finite))min(z[finite])else NA_real_,maximum=if(any(finite))max(z[finite])else NA_real_,mean=if(any(finite))mean(z[finite])else NA_real_,standard_deviation=if(sum(finite)>1)stats::sd(z[finite])else NA_real_,quantiles=qs,hard_range_valid=hard_valid,soft_range_warning=soft_warning,non_na_count=sum(finite)) }
normalize_output_values <- function(x, variable_spec, config=NULL) { if (!(variable_spec$id %in% c("era5_soilmoist","era5_lai_low","agera5_relhum_min"))) return(validate_variable_values(x,variable_spec)); z<-as.numeric(x); finite<-is.finite(z); v<-if(is.null(config)) list() else (config$validation %||% list()); minv<-v$physical_minimum %||% v$physical_minimum_percent %||% variable_spec$hard_valid_range[1]; maxv<-v$physical_maximum %||% v$physical_maximum_percent %||% variable_spec$hard_valid_range[2]; tol<-v$clamp_tolerance %||% v$clamp_tolerance_percent %||% if(variable_spec$id=="era5_lai_low") 0.01 else if(variable_spec$id=="agera5_relhum_min") 0.5 else 0.01; before<-z[finite]; if(any(before<minv-tol|before>maxv+tol)) stop("Final values outside physical tolerance",call.=FALSE); low<-finite&z<minv; high<-finite&z>maxv; low_adj<-if(any(low))max(abs(z[low]-minv))else 0; high_adj<-if(any(high))max(abs(z[high]-maxv))else 0; z[low]<-minv; z[high]<-maxv; final<-z[is.finite(z)]; if(length(final)&&any(final<minv|final>maxv))stop("Final values outside physical range",call.=FALSE); list(values=z,projected_masked_minimum_before_clamp=if(length(before))min(before)else NA_real_,projected_masked_maximum_before_clamp=if(length(before))max(before)else NA_real_,projected_minimum_before_adjustment=if(length(before))min(before)else NA_real_,projected_maximum_before_adjustment=if(length(before))max(before)else NA_real_,cells_adjusted_low=sum(low),cells_clamped_low=sum(low),cells_clamped_high=sum(high),largest_low_adjustment=low_adj,largest_high_adjustment=high_adj,final_minimum=if(length(final))min(final)else NA_real_,final_maximum=if(length(final))max(final)else NA_real_,non_na_count=length(final),hard_range_valid=TRUE,soft_range_warning=FALSE) }
aggregate_daily_values <- function(rasters, variable_spec) { if(variable_spec$daily_statistic=="daily_minimum")return(terra::app(terra::rast(rasters),fun=min,na.rm=TRUE));if(variable_spec$daily_statistic=="daily_mean")return(terra::app(terra::rast(rasters),fun=mean,na.rm=FALSE));stop("Unsupported daily statistic: ",variable_spec$daily_statistic,call.=FALSE) }
aggregate_weekly_values <- function(rasters, variable_spec) { if(variable_spec$weekly_statistic=="minimum")return(terra::app(terra::rast(rasters),fun=min,na.rm=TRUE));if(variable_spec$weekly_statistic=="mean")return(terra::app(terra::rast(rasters),fun=mean,na.rm=FALSE));stop("Unsupported weekly statistic: ",variable_spec$weekly_statistic,call.=FALSE) }
daily_output_filename <- function(variable_spec,date,estimated=FALSE)format_daily_filename(variable_spec$daily_filename_prefix,date,estimated)
weekly_output_filename <- function(variable_spec,iso_year,iso_week,estimated=FALSE)format_weekly_filename(variable_spec$weekly_filename_prefix,iso_year,iso_week,estimated)
