aggregate_daily_to_weekly <- function(daily_dir, weekly_dir, prefix = "mintemp", iso_weeks = NULL, require_complete_week = TRUE, overwrite = TRUE, template_path, rebuild_all = FALSE, inventory = NULL, inventory_source = "post_process", variable_spec = NULL, config = NULL) {
  spec <- variable_spec %||% get_variable_spec(if (prefix == "soilmoist") "era5_soilmoist" else "era5_mintemp", config)
  inv <- inventory %||% inventory_grid_directory(daily_dir, spec$daily_filename_prefix, "daily", FALSE)
  if ("observed_valid" %in% names(inv)) inv <- inv[inv$observed_valid %in% TRUE, , drop = FALSE] else inv <- inv[inv$valid & !inv$estimated, , drop = FALSE]
  inv <- inv[!is.na(inv$date) & !inv$estimated, , drop = FALSE]
  if (!nrow(inv)) return(list(status = "success_noop", written = character(), reused = character(), replaced = character(), incomplete_weeks = data.frame(), complete_weeks = character(), affected_iso_weeks = character(), failed = character(), reason = "no_valid_daily_products", inventory_source = inventory_source, inventory_rows_received = nrow(inventory %||% inv), valid_daily_rows_received = 0L, valid_daily_dates_received = character()))
  inv$date <- normalize_date_vector(inv$date, "inventory_dates")
  if (anyDuplicated(format(inv$date, "%Y-%m-%d"))) stop("Duplicate valid observed daily dates cannot be aggregated", call. = FALSE)
  if (rebuild_all || is.null(iso_weeks)) iso_weeks <- identify_affected_iso_weeks(inv$date)
  assessment <- assess_iso_week_completeness(inv$date); assessment <- assessment[assessment$week_id %in% iso_weeks, , drop = FALSE]
  incomplete <- assessment[!assessment$complete, , drop = FALSE]; complete <- assessment[assessment$complete, , drop = FALSE]
  if (isTRUE(require_complete_week) && nrow(incomplete) > 0L && nrow(complete) == 0L) return(list(status = "success_noop", written = character(), reused = character(), replaced = character(), incomplete_weeks = incomplete, complete_weeks = character(), affected_iso_weeks = incomplete$week_id, failed = character(), reason = "incomplete_week", inventory_source = inventory_source, inventory_rows_received = nrow(inventory), valid_daily_rows_received = nrow(inv), valid_daily_dates_received = format(inv$date, "%Y-%m-%d")))
  template <- terra::rast(template_path); support_info <- if (!is.null(config) && exists("era5land_support_mask_info", mode = "function")) era5land_support_mask_info(config, template, required = FALSE) else NULL; support_mask <- if (is.null(support_info)) NULL else support_info$mask; template_sha <- template_fingerprint(template)$sha256; support_mask_sha <- if (is.null(support_info)) NULL else support_info$support_mask_sha256
  fs::dir_create(weekly_dir, recurse = TRUE); written <- reused <- replaced <- failed <- character(); selected_paths <- list(); match_records <- list(); algorithm <- "weekly-v3-support-mask"
  for (i in seq_len(nrow(complete))) {
    w <- complete$week_id[i]; expected_dates <- normalize_date_vector(complete$expected_dates[[i]], "expected_dates"); inventory_dates <- normalize_date_vector(inv$date, "inventory_dates"); expected_keys <- format(expected_dates, "%Y-%m-%d"); inventory_keys <- format(inventory_dates, "%Y-%m-%d"); match_counts <- vapply(expected_keys, function(key) sum(inventory_keys == key), integer(1)); match_records[[w]] <- match_counts
    if (!all(match_counts == 1L)) stop("Expected exactly one valid daily raster per date for ", w, call. = FALSE)
    week_rows <- inv[match(expected_keys, inventory_keys), , drop = FALSE]; daily_paths <- week_rows$path; selected_paths[[w]] <- daily_paths; daily_hashes <- weekly_daily_sha256(daily_paths); fp <- weekly_input_fingerprint(w, spec, expected_dates, daily_hashes, template_sha, algorithm, support_mask_sha); out <- file.path(weekly_dir, weekly_output_filename(spec, complete$iso_year[i], complete$iso_week[i])); sidecar <- paste0(out, ".json")
    can_reuse <- FALSE
    if (file.exists(out) && file.exists(sidecar)) {
      sc <- tryCatch(jsonlite::read_json(sidecar, simplifyVector = TRUE), error = function(e) NULL); r <- tryCatch(terra::rast(out), error = function(e) NULL); coverage <- if (!is.null(r)) tryCatch(validate_template_coverage(r, template, TRUE, support_mask = support_mask), error = function(e) e) else NULL
      can_reuse <- !is.null(sc) && !is.null(r) && !inherits(coverage, "error") && terra::nlyr(r) == 1L && identical(as.character(sc$input_fingerprint), fp) && identical(as.character(sc$variable_spec_hash), spec$variable_spec_hash) && identical(as.character(sc$template_sha256), template_sha) && identical(as.character(sc$support_mask_sha256 %||% NULL), as.character(support_mask_sha %||% NULL))
    }
    if (can_reuse) { reused <- c(reused, out); next }
    if (file.exists(out)) replaced <- c(replaced, out)
    for (path in daily_paths) { r <- terra::rast(path); if (!terra::compareGeom(r, template, stopOnError = FALSE)) stop("Daily raster geometry does not match template: ", path); validate_template_coverage(r, template, TRUE, support_mask = support_mask) }
    weekly <- aggregate_weekly_values(daily_paths, spec); tmp <- paste0(out, ".tmp.tif"); terra::writeRaster(weekly, tmp, overwrite = TRUE, wopt = list(datatype = "FLT4S", gdal = c("COMPRESS=DEFLATE", "PREDICTOR=3", "TILED=YES"))); if (!file.exists(tmp)) stop("Weekly temporary raster was not created: ", w); if (file.exists(out)) unlink(out); if (!file.rename(tmp, out)) stop("Could not promote weekly output: ", w)
    check <- validate_weekly_output(out, complete$iso_year[i], complete$iso_week[i], template, list(project = list(dataset_id = spec$id), validation = list(minimum = spec$hard_valid_range[1], maximum = spec$hard_valid_range[2], minimum_celsius = spec$hard_valid_range[1], maximum_celsius = spec$hard_valid_range[2], require_exact_template_geometry = TRUE)), spec); if (!check$valid) stop("Weekly validation failed: ", w, "; ", check$message); validate_template_coverage(out, template, TRUE, support_mask = support_mask)
    out_sha <- digest::digest(file = out, algo = "sha256"); jsonlite::write_json(list(week_id = w, variable_id = spec$id, variable_spec_hash = spec$variable_spec_hash, weekly_statistic = spec$weekly_statistic, template_sha256 = template_sha, support_mask_sha256 = support_mask_sha, unsupported_cells = support_info$unsupported_cells %||% integer(), selected_daily_dates = as.character(expected_dates), selected_daily_paths = daily_paths, selected_daily_sha256 = unname(daily_hashes), aggregation_algorithm_version = algorithm, input_fingerprint = fp, output_sha256 = out_sha, created_utc = format(Sys.time(), tz = "UTC")), sidecar, pretty = TRUE, auto_unbox = TRUE); if (!out %in% replaced) written <- c(written, out)
  }
  list(status = if (length(written) || length(reused)) "success" else "success_noop", written = written, reused = reused, replaced = replaced, affected_iso_weeks = unique(c(incomplete$week_id, complete$week_id)), incomplete_weeks = incomplete, complete_weeks = complete$week_id, failed = failed, reason = if (nrow(incomplete)) "some_incomplete_weeks" else NULL, inventory_source = inventory_source, inventory_rows_received = nrow(inventory %||% inv), valid_daily_rows_received = nrow(inv), valid_daily_dates_received = format(inv$date, "%Y-%m-%d"), expected_dates = if (length(match_records)) lapply(complete$expected_dates, normalize_date_vector) else list(), match_counts = match_records, selected_daily_paths = selected_paths, variable_spec_hash = spec$variable_spec_hash, weekly_outputs_replaced = length(replaced), support_provenance = if (is.null(support_info)) list() else era5land_support_provenance(config))
}
